apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp240731
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp240731 
  name: goapp240731
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goapp240731
    weight: 100 
